# ═══════════════════════════════════════════════════════
# CONFIG_GENOME — Thousand Lives Game DNA
# ═══════════════════════════════════════════════════════
# Extracted from simulation data: thousand-lives-sim.html
# Distilled to: playable poem architecture
# ═══════════════════════════════════════════════════════

meta:
  title: "thousand lives — trial and rebirth"
  subtitle: "a turtle learns to die beautifully"
  seed: 9999
  version: "0.9.9"
  generation: "inceptor-01"

# ═══════════════════════════════════════════════════════
# CORE LOOP — The Grammar of Learning
# ═══════════════════════════════════════════════════════

core_loop: "perceive → infer → act → surprise → adapt → reincarnate"

# ═══════════════════════════════════════════════════════
# AGENTS — Who Acts
# ═══════════════════════════════════════════════════════

agents:
  - id: "turtle"
    name: "Thousand"
    role: "learner"
    embodiment: "circular · glowing · seeking"
    
  - id: "environment"
    name: "Apartment"
    role: "teacher"
    embodiment: "grid · shadow · affordance"
    
  - id: "disruptor"
    name: "Chalice"
    role: "chaos"
    embodiment: "flash · scatter · uncertainty"

# ═══════════════════════════════════════════════════════
# FORCES — What Drives
# ═══════════════════════════════════════════════════════

forces:
  hunger:
    urgency: 1.0
    decay_rate: 0.1
    satisfaction: "nourishing objects"
    color: "#4cffb1"
    
  energy:
    urgency: 0.8
    decay_rate: 0.05
    satisfaction: "rest · stillness"
    color: "#9afcc7"
    
  safety:
    urgency: 1.1
    decay_rate: 0.0
    satisfaction: "distance from threat"
    color: "#ff6e8c"
    
  curiosity:
    urgency: 0.7
    decay_rate: -0.02  # grows over time
    satisfaction: "unknown objects"
    color: "#ffce63"
    
  certainty:
    urgency: 0.9
    decay_rate: 0.03
    satisfaction: "confirmed beliefs"
    color: "#9effa7"

# ═══════════════════════════════════════════════════════
# AFFORDANCES — What Objects Offer
# ═══════════════════════════════════════════════════════

object_vocabulary:
  nourishing:
    examples: ["grapes", "pellets", "bumpy-fruit"]
    valence: 0.8
    feedback: "pleasure · satiation"
    shape: "circle"
    
  threatening:
    examples: ["urchin", "toxic", "security-bug"]
    valence: -0.9
    feedback: "pain · recoil"
    shape: "star · spikes"
    
  neutral:
    examples: ["bottle", "jar", "monitor"]
    valence: 0.0
    feedback: "indifference"
    shape: "rectangle"
    
  ambiguous:
    examples: ["bumpy-fruit", "unknown-substance"]
    valence: 0.0
    feedback: "surprise · learning"
    shape: "polygon · irregular"

# ═══════════════════════════════════════════════════════
# GOAL — What Matters
# ═══════════════════════════════════════════════════════

goal: "minimize surprise across lifetimes"

paradox: "death renews learning"

success_condition: "graceful adaptation to the unknowable"

# ═══════════════════════════════════════════════════════
# AESTHETICS — How It Feels
# ═══════════════════════════════════════════════════════

mood: ["wonder", "melancholy", "persistence"]

palette:
  name: "midnight-sun"
  colors:
    background: "#040f0e"
    turtle: "#4cffb1"
    nourishing: "#9effa7"
    threatening: "#ff6e8c"
    neutral: "#9afcc7"
    light: "rgba(76, 255, 177, 0.18)"

audio:
  scale: "whole-tone-dream"
  instruments:
    surprise: "pluck · bright"
    pleasure: "warm-pad"
    pain: "dissonant-stab"
    death: "reverb-wash"
    rebirth: "gentle-arpeggio"

# ═══════════════════════════════════════════════════════
# RULES — How It Works
# ═══════════════════════════════════════════════════════

rules:
  - "objects have no labels · only shape and color"
  - "beliefs form through interaction · not instruction"
  - "drives compete · highest urgency wins"
  - "death occurs at zero hunger or energy"
  - "rebirth flushes 20% of beliefs"
  - "chalice appearance scrambles all positions"
  - "motion is minimal · 2-3 pixels per tick"
  - "time cycles through day/night · light shifts"

# ═══════════════════════════════════════════════════════
# INTERACTION MODES — How To Touch
# ═══════════════════════════════════════════════════════

interaction_modes:
  - mode: "tap"
    effect: "spawn new object"
    
  - mode: "swipe"
    effect: "trigger chalice disruption"
    
  - mode: "hover"
    effect: "reveal object aura (no text)"
    
  - mode: "tilt"
    effect: "shift light gradient"

# ═══════════════════════════════════════════════════════
# VISUAL LANGUAGE — Symbol Grammar
# ═══════════════════════════════════════════════════════

visual_language:
  turtle: "pulsing circle · glow intensity = arousal"
  objects: "geometric shapes · color = valence"
  grid: "faint lines · spatial reference"
  light: "radial gradient · time of day"
  death: "white flash → fade"
  rebirth: "center emergence · soft glow"

# ═══════════════════════════════════════════════════════
# MUTATION OPS — How Children Differ
# ═══════════════════════════════════════════════════════

mutation_ops:
  - "invert_goal"          # maximize surprise instead
  - "mirror_axis"          # flip world horizontally
  - "slow_time"            # halve tick speed
  - "spawn_echo"           # duplicate turtle with offset
  - "simplify_rules"       # remove one force
  - "transmute_color"      # shift palette hue
  - "cohere_loop"          # tighten feedback delays

# ═══════════════════════════════════════════════════════
# RUBRIC — How To Score
# ═══════════════════════════════════════════════════════

rubric_weights:
  joy: 1.5              # satisfying interactions
  flow: 1.3             # smooth movement logic
  surprise: 1.2         # unexpected moments
  accessibility: 1.4    # no text required
  elegance: 1.6         # minimal code · maximal expression

# ═══════════════════════════════════════════════════════
# RECURSION CONFIG
# ═══════════════════════════════════════════════════════

recursion:
  max_ttl: 3
  beam_width: 3
  select_top_k: 1
  ttl_decay: true
  export_single_file: true

# ═══════════════════════════════════════════════════════
# CDN RESOURCES
# ═══════════════════════════════════════════════════════

cdn:
  three: "https://unpkg.com/three@0.161.0/build/three.min.js"
  tone: "https://unpkg.com/tone@14.8.49/build/Tone.js"

# ═══════════════════════════════════════════════════════
# PHILOSOPHY
# ═══════════════════════════════════════════════════════

philosophy: "game == poem you can touch"

principles:
  - "every system → playable"
  - "every play → new system"
  - "text is violence to sensation"
  - "geometry speaks"
  - "sound reveals"
